language: java

os: linux

jdk:
  - openjdk8

install:
  - mvn package

script:
  - docker build -t shubhamtricon/quarkus-vs-spring:$TRAVIS_BUILD_ID .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag shubhamtricon/quarkus-vs-spring:$TRAVIS_BUILD_ID shubhamtricon/quarkus-vs-spring:$TRAVIS_BUILD_ID
  - docker push shubhamtricon/quarkus-vs-spring:$TRAVIS_BUILD_ID